### ISSUE TITLE
Looking for an Option to minimize without deleting variables.

### ISSUE THREAD

**Issue by tekeuange23** [meelgroup/arjun#10]
### Documentation 

The docs says by setting `--renumber` to `0`, it avoid renumbering of variables so I can keep track of a deleted variable if it ever happened.

### Question 

Is there an option or a way to avoid searching for independent set by deleting variables ?

Cheers!

Mate

**Comment by msoos** [comment]
Please run with

```
./arjun --bve 0 --renumber 0 myfile.cnf > simplified.cnf
```

I hope the above helped,

Mate
