### ISSUE TITLE
CNF with 0 clauses output

### ISSUE THREAD

**Issue by allrtaken** [meelgroup/arjun#2]
Hello,

I ran arjun with default parameters on the file mc2022_track1_001.cnf and got the file output.cnf with 0 clauses as output. I am not sure what the issue is or if I am running the tool incorrectly. The command I used was 
`./arjun --input mc2022_track1_001.cnf output.cnf`

I have also attached the output of the tool.

Thanks,
Aditya
[issue_files.zip](https://github.com/meelgroup/arjun/files/9767634/issue_files.zip)

**Comment by msoos** [comment]
Hi,

Well, if Arjun is correct, there are 2**100 solutions: it spits out an empty CNF with 100 variables and an independent support of 100. So 2*100 solutions. My understand is that that's correct. Hence, Arjun is doing what it was designed to do: simplify the CNF while preserving the solution count.

Unless I am wrong about the number of solutions of that CNF, Arjun is working correctly. Arjun can be this powerful, actually :) [or it's buggy :D hopefully not!]

I hope this helps,

Mate

**Comment by ryap** [comment]
On Thu, Oct 13, 2022 at 06:25:55AM -0700, Mate Soos wrote:
>    Hi,
> 
>    Well, if Arjun is correct, there are 2**100 solutions: it spits out an
>    empty CNF with 100 variables and an independent support of 100. So 2*100
>    solutions. My understand is that that's correct. Hence, Arjun is doing
>    what it was designed to do: simplify the CNF while preserving the solution
>    count.
> 
>    Unless I am wrong about the number of solutions of that CNF, Arjun is
>    working correctly. Arjun can be this powerful, actually :) [or it's buggy
>    :D hopefully not!]

Can run another counter to check.

R

**Comment by msoos** [comment]
I did, it didn't finish.

Mate
