### ISSUE TITLE
[Feature Request] Mapping between variables of original and new formulas

### ISSUE THREAD

**Issue by allrtaken** [meelgroup/arjun#3]
Hello,

Along with the smaller CNF, it will be helpful to get a mapping to the variables of the original formula, which can potentially help with sampling, weighted counting etc. Similarly, even for empty occurrences, it would be useful to know which variables they were (for eg for weighted counting when the weights don't sum to 1).

Thanks,
Aditya

**Comment by msoos** [comment]
One thing to keep in mind. Let's say that it turns out that `a==-b`. Of course, Arjun will only leave `a` in the formula. So... it'll be a multi-map, like:
```
x ->  a, -b
y ->  c, d, e, -f
...
```

The other thing I can do is skip the renumbering. Then you have the CNF in the original variables. I am doing the latter now. It's not as powerful, but it's a LOT easier to deal with. However, solvers like GANAK etc. may not be *as fast* this way. But you don't have to deal with the multi-map.

**Comment by msoos** [comment]
OK, as you can see, the solution where we don't renumber has now been added with 1190e8aa69c25fb458ddba9bdb6bc1cb24873f22 . You can add the parameter `--renumber 0`. This way, if a=b, both will be in the CNF, but there will be 2 clauses:

```
a -b 0
-a b 0
```

This is **EXPERIMENTAL**, you need to send me examples where it's wrong. And it may well be wrong. We are in the process of doing work to make sure we can find bugs in things like this, but that work is not yet finished. If you find a bug, please write a new issue with:
* CNF that triggers it
* The expected count
* The actual count
* What you think may be happening/some analysis

I hope the above helps,

Mate

**Comment by msoos** [comment]
NOTE: the advantage of `--renumber 0` is that you can use tools directly on the CNF produced, no translation needed. A sample will be a sample. However, obviously, if the original problem had 10k variables, you'll still have 10k variables. The number of clauses could be _significantly_ smaller, though, and unit clauses will be added that are unit, etc.

**Comment by allrtaken** [comment]
Thank you, I will experiment with no renumbering. Just to mention, I don't mind dealing with a multi-map in case it is easy to output. While a reduction in the number of clauses is certainly useful, fewer variables would also be of help for the tools I am working with. 

Thanks,
Aditya
