### ISSUE TITLE
How to run example instance

### ISSUE THREAD

**Issue by tekeuange23** [meelgroup/arjun#9]
### Documentation example says

``````
./arjun input.cnf output.cnf
c [arjun] original sampling set size: 500
c ind 1 4 5 20 31 0
[...]
c [arjun] Done dumping. T: 1.0406
``````

### My Question ???

Is it a command line? If so, where is located the `./arjun` file after successfully completed the build process?

Cheers!

Mate

**Comment by msoos** [comment]
Hi,

The `arjun` binary is located in the `build` folder after building.

I hope this helps,

Mate
